### ISSUE TITLE
PHP Deprecated Errors

### ISSUE THREAD

**Issue by s22-tech** [giventofly/teikirize-bookmarks#2]
I've run across a couple of errors while testing out this script that you might want to be aware of:

```
PHP Deprecated:  Automatic conversion of false to array is deprecated in /home/www/vendor/delight-im/auth/src/Auth.php on line 1781
```

```
PHP Deprecated:  Automatic conversion of false to array is deprecated in /home/www/core/core.php on line 139
```

And you may want to specifically point out that PHP requires the iconv extension.  I received this error before I realized it wasn't activated on my server:
```
PHP Fatal error:  Uncaught Error: Call to undefined function iconv() in /home/www/core/core.php:71
Stack trace:
#0 /home/www/core/bookmarks.php(15): slugify('web-site')
#1 /home/www/core/bookmarks.php(160): insert_tag('web-site')
#2 /home/www/core/api.php(111): insert_bookmark('[https://www.ert...', 'Descr, ...', '/graphics/auth-...', 'Atlas Foun...', '', '](https://www.sup...',%20'wire%20shelving,%20...',%20'/graphics/auth-...',%20'Superior%20Shelvi...',%20'',%20')', Array)
#3 /home/www/core/routes.php(80): api_call('manage')
#4 /home/www/index.php(60): routes(Array)
#5 {main}
  thrown in /home/www/core/core.php on line 71
```

PHP 8.3.4
SQLite 3.7.17
Apache 2.4.58

**Comment by giventofly** [comment]
Sorry for the delay.

Iconv is usually loaded by default in all php installations, I didn't tested yet with 8.3 but will do that in the future and fix those errors and probably also implement some new features that I'm currently missing and want to implement.

thanks for the heads up
